"""Render docs/EVALUATION.md from out/evaluation.json.

Separate from run_eval.py so the document can never contain a number that was
not written to disk by a run, and so it can be regenerated without re-scoring.

The held-out errors are CATEGORISED here rather than fixed. Adding a rule to
pass a held-out case converts that case into development data and the held-out
score stops meaning anything; the categories below are what I would fix and
what class of problem each represents, which is the useful information anyway.

Run:  python write_report.py     (after run_eval.py)
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))
from lexicon import ASSERTIONS

OUT, DOC = "out", "docs/EVALUATION.md"

ERROR_CATEGORIES = {
    15: ("scope termination",
         "The `s/p` historical scope runs past 'now on' and swallows the "
         "current medications, marking active drugs as completed. A historical "
         "scope should terminate at a present-tense pivot, and 'now', "
         "'currently' and 'today' are not in TERMINATION. This is the "
         "highest-severity of the three: it silently changes a live medication "
         "list into a historical one."),
    24: ("dictionary partition",
         "Any drug can be an allergen, but drugs live in MEDICATION_TERMS and "
         "allergens in ALLERGEN_TERMS, so 'intolerance to metformin' resolves "
         "to a medication rather than an allergy. The partition is the bug: "
         "allergen is a ROLE a concept plays in a context, not a separate "
         "vocabulary. Fixing it properly means making the allergy context "
         "promote any drug mention, which is a design change rather than a "
         "lexicon addition."),
    27: ("lexicon coverage",
         "'Neither X nor Y' is not in NEGATION_FORWARD. A pure coverage gap, "
         "and the characteristic failure of rule-based negation: it fails on "
         "phrasings nobody enumerated, and it fails SILENTLY by returning "
         "`present` -- the most dangerous possible default, because a missed "
         "negation becomes an asserted diagnosis."),
}


def main():
    os.makedirs("docs", exist_ok=True)
    d = json.load(open(f"{OUT}/evaluation.json"))
    held, adv, mp = d["heldout"], d["adversarial"], d["mapping"]

    L = ["# Evaluation", "",
         "Generated by `write_report.py` from `out/evaluation.json`. Every "
         "number is produced by `run_eval.py`; none are asserted.", "",
         "## Entity-level performance", "",
         "| set | cases | exact-case | P | R | F1 | relaxed F1 |",
         "|---|---|---|---|---|---|---|"]
    for name, r in [("**HELD-OUT**", held), ("adversarial (dev)", adv)]:
        L.append(f"| {name} | {r['n_cases']} | "
                 f"{r['exact_case_match']/r['n_cases']:.0%} | "
                 f"{r['exact'][0]:.3f} | {r['exact'][1]:.3f} | "
                 f"{r['exact'][2]:.3f} | {r['relaxed'][2]:.3f} |")
    L += ["",
          "**The held-out row is the number.** The adversarial row is a ceiling.",
          "",
          "Six adversarial cases failed on the first run and the extractor was "
          "changed until they passed, so that row measures how well the rules "
          "fit the cases used to write them -- the rule-based equivalent of "
          "reporting training accuracy. The held-out sentences were written "
          "afterwards in a single pass, scored once, and nothing was fixed "
          "afterwards.",
          "",
          "Exact matching requires concept + kind + assertion all correct. "
          "Relaxed ignores assertion. The gap between those two columns "
          "isolates the ConText layer from the dictionary, which matters "
          "because they fail for different reasons and a single F1 hides "
          "which one is broken.",
          "",
          "## Assertion confusion matrix (held-out)", "",
          "| true \\ predicted | " + " | ".join(ASSERTIONS) + " |",
          "|---" * (len(ASSERTIONS) + 1) + "|"]
    conf = held["confusion"]
    for a in ASSERTIONS:
        row = conf[a]
        if sum(row.values()) == 0:
            continue
        L.append(f"| **{a}** | " + " | ".join(str(row[b]) for b in ASSERTIONS) + " |")
    n_abs = sum(conf["absent"].values())
    L += ["",
          f"- absent to present leakage: **{conf['absent']['present']}/{n_abs}** "
          f"({conf['absent']['present']/n_abs if n_abs else 0:.1%})",
          f"- family to present leakage: **{conf['family']['present']}**", "",
          "These two cells are not interchangeable with the rest of the matrix, "
          "or with each other.",
          "",
          "A false `present` in a risk-adjustment pipeline becomes a submitted "
          "diagnosis, and a submitted diagnosis unsupported by the record is "
          "potential false-claims exposure -- a legal problem, not a metrics "
          "problem. A false `absent` is a missed condition: worse for the "
          "patient clinically, worse for the plan financially, and not a "
          "compliance event. Which system consumes the output decides which "
          "error you tune against, and reporting one F1 hides that the "
          "decision exists.",
          "",
          "## Terminology mapping", "",
          f"- distinct concepts extracted: **{mp['n_concepts']}**",
          f"- mapped to SNOMED CT / RxNorm: **{mp['n_mapped']}**",
          f"- hit rate: **{mp['hit_rate']:.1%}**", "",
          "Unmapped concepts, with occurrence counts:", "",
          "| kind | concept | n |", "|---|---|---|"]
    for pair, n in mp["misses"]:
        kind, concept = pair
        L.append(f"| {kind} | `{concept}` | {n} |")
    L += ["",
          "Every row above was RECOGNISED by the extractor and could not be "
          "coded. The `CodeableConcept` still carries the original text (by "
          "design in `fhir_out._codeable`), so a human reviewer can repair it "
          "-- but any query that filters on a code will not see these patients "
          "at all. That is silent data loss rather than an error anyone gets "
          "paged about, and it is why mapping failure analysis belongs in the "
          "evaluation and not in a footnote.",
          "",
          "The hit rate is a property of the vendored subset in `lexicon.py`, "
          "**not** of SNOMED CT. In production the release is loaded whole and "
          "version-pinned, and mapping is re-run when the version changes, "
          "because concepts get inactivated and replaced.",
          "",
          "## FHIR emission", "", "| resource | n |", "|---|---|"]
    for rt, c in sorted(d["fhir"]["counts"].items()):
        L.append(f"| {rt} | {c} |")
    L += [f"| *deliberately dropped (hypothetical findings)* | "
          f"{d['fhir']['dropped']} |", "",
          f"- shape-lint problems: **{len(d['fhir']['lint_problems'])}**",
          f"- family-history findings emitted as a patient `Condition` in the "
          f"same note: **{d['fhir']['family_leaked_to_patient_conditions']}**",
          "",
          "That last line is the case a screener checks by hand. Family history "
          "is routed to `FamilyMemberHistory` and never becomes a patient "
          "`Condition`; it is asserted in `tests/test_nlp.py`, not merely "
          "printed here.",
          "",
          "The shape lint is **not** FHIR validation. The official HL7 "
          "validator is a Java application resolving real StructureDefinitions "
          "and terminology servers, and it is not run here. The lint checks the "
          "specific invariants a hand-built mapper can break -- required "
          "fields, valid status codes, and `clinicalStatus` wrongly present on "
          "a refuted Condition. Calling it validation would be the overclaim.",
          "",
          f"Throughput: **{d['throughput_sentences_per_sec']:,.0f} "
          f"sentences/sec** single-core.",
          "",
          "## Held-out errors, not fixed", "",
          "Fixing these would convert them into development data and the "
          "held-out score would stop meaning anything. They are categorised "
          "instead, which is the more useful artefact: the category tells you "
          "what class of problem the system has, where a patch would only tell "
          "you that one sentence now works.", ""]
    for err in d["heldout_errors"]:
        cat, why = ERROR_CATEGORIES.get(err["index"], ("uncategorised", ""))
        L += [f"### [{err['index']}] {cat}", "", f"> {err['text']}", ""]
        if err["missed"]:
            L.append(f"- missed: `{err['missed']}`")
        if err["spurious"]:
            L.append(f"- spurious: `{err['spurious']}`")
        for w in err.get("wrong_assertion", []):
            L.append(f"- `{w['concept']}`: expected **{w['expected']}**, "
                     f"got **{w['got']}**")
        if why:
            L += ["", why]
        L.append("")

    L += ["## What a kappa would have caught, and is not reported", "",
          "The gold sets have a single annotator: me. There is no second "
          "annotator, so no inter-annotator agreement, and the repeated-pass "
          "intra-annotator kappa the spec asks for is not fakeable in one "
          "session and is **not reported** rather than invented.",
          "",
          "What that leaves unmeasured is specific, not vague. Several "
          "annotations in `gold/adversarial.py` are genuinely arguable -- most "
          "of all rule 3, that a negated family history stays `family` rather "
          "than becoming `absent`. A kappa would have quantified how "
          "consistently I applied that rule across 105 sentences written over "
          "a few hours. Without it, every F1 above inherits an unknown amount "
          "of annotator inconsistency, and the honest reading is that the "
          "held-out number has an error bar I cannot put a figure on.", ""]

    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"wrote {DOC} ({len(L)} lines)")


if __name__ == "__main__":
    main()
