"""Trigger lexicons, clinical dictionaries, and a terminology subset.

NO REAL CLINICAL TEXT IS USED ANYWHERE IN THIS PROJECT, and that is worth
stating first because it is the most important fact about it. Real clinical
notes are PHI. They cannot be put in a portfolio repository, cannot be pasted
into an API, and cannot be shared with a colleague for a second opinion. Every
sentence in this project is either generated by `src/notes.py` from templates I
wrote, or hand-authored by me in `gold/adversarial.py`.

TERMINOLOGY SCOPE NOTE
----------------------
SNOMED CT is licensed (free in UMLS member countries via the UMLS Metathesaurus,
but licensed) and RxNorm is a download. Neither is vendored here. `SNOMED` and
`RXNORM` below are small hand-built subsets using REAL concept identifiers where
I am confident of them, and they are used to demonstrate the mapping STEP and,
more importantly, its failure modes. A production system loads the real
releases, pins the version, and re-runs mapping when the version changes,
because concepts get inactivated and replaced.

The mapping hit-rate reported by `run_eval.py` is therefore a property of this
subset's coverage, not of SNOMED's.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# ConText trigger lexicons.
#
# The algorithm (Chapman et al.) is: a trigger opens a scope that propagates
# forward or backward until a termination term or a sentence boundary. The
# lexicon is the whole game -- the algorithm is twenty lines and the trigger
# lists are where the clinical knowledge lives.
# ---------------------------------------------------------------------------

# Negation triggers that scope FORWARD: "no evidence of X"
NEGATION_FORWARD = [
    "no evidence of", "no evidence for", "no sign of", "no signs of",
    "not evidence of", "no complaints of", "no findings of", "no", "not",
    "denies", "denied", "without", "absent", "negative for", "free of",
    "rules out", "ruled out", "r/o negative", "resolved", "no longer",
    "declines", "unremarkable for", "fails to reveal", "no suspicious",
    "without evidence of", "no indication of", "not have", "no history of",
]

# Negation triggers that scope BACKWARD: "chest pain is absent"
NEGATION_BACKWARD = [
    "ruled out", "excluded", "not identified", "not detected",
    "is ruled out", "are ruled out", "was ruled out", "were ruled out",
    "is absent", "are absent", "was absent", "were absent", "is negative",
    "are negative", "not seen", "not present", "not appreciated",
    "was not demonstrated", "is unlikely", "have been ruled out",
]

# PSEUDO-negation: contains a negation phrase but is NOT one. These must be
# matched FIRST and consume the span, or "no increase in pain" negates "pain".
# This list is the difference between a negation detector and a string search.
PSEUDO_NEGATION = [
    "no increase", "no significant change", "no change", "no interval change",
    "not only", "no further", "not necessarily", "gram negative",
    "gram-negative", "no definite change", "gram stain negative",
    "gram positive", "not extend", "not cause", "no new",
    "cannot be excluded", "can not be excluded", "cannot be ruled out",
    "not ruled out", "no significant interval change", "not drain",
    "cannot exclude", "unable to exclude", "can not exclude",
]

# Termination terms close an open scope early: "no chest pain but has dyspnea"
TERMINATION = [
    "but", "however", "nevertheless", "though", "although", "aside from",
    "apart from", "except", "yet", "still", "otherwise", "which",
    "reveals", "revealed", "secondary to", "as a cause for", "cause for",
    "causes for", "etiology for", "source for", "trigger event for",
    "origin for",
]

# Family / other-subject experiencer
FAMILY = [
    "family history", "family hx", "fh", "fhx", "mother", "father", "sister",
    "brother", "sibling", "siblings", "son", "daughter", "aunt", "uncle",
    "grandmother", "grandfather", "cousin", "maternal", "paternal",
    "parents", "grandparent", "in her family", "in his family",
    "in their family",
]

# Historical / not-current
HISTORICAL = [
    "history of", "hx of", "h/o", "past medical history", "pmh", "pmhx",
    "status post", "s/p", "previous", "previously", "prior", "in the past",
    "years ago", "year ago", "months ago", "month ago", "remote history",
    "childhood", "as a child", "resolved in", "since childhood",
]

# Hypothetical / conditional
HYPOTHETICAL = [
    "if", "should", "in case of", "in the event of", "return if",
    "come back if", "call if", "unless", "as needed for", "prn for",
    "were to", "in case", "advised to return for", "watch for",
    "instructed to return if", "seek care if",
]

# Uncertainty / possible
POSSIBLE = [
    "possible", "possibly", "probable", "probably", "likely", "suspicious for",
    "suspected", "concerning for", "consistent with", "may represent",
    "cannot be excluded", "cannot be ruled out", "questionable", "versus",
    "vs", "differential includes", "worrisome for", "equivocal",
    "rule out", "r/o", "presumed", "apparent", "cannot exclude",
    "unable to exclude", "cannot be excluded", "can not exclude",
]

# Trailing modifiers scope BACKWARD over the entity that precedes them.
# "Asthma since childhood" and "NIDDM noted on prior admission" carry their
# temporal marker after the finding, which a forward-only ConText misses
# entirely -- and misses silently, by returning `present`.
HISTORICAL_BACKWARD = [
    "since childhood", "in the past", "years ago", "year ago", "months ago",
    "month ago", "on prior admission", "on previous admission",
    "in remission", "since adolescence", "as a child", "resolved",
]
HYPOTHETICAL_BACKWARD = ["prn", "as needed", "if needed", "as required"]

ASSERTIONS = ["present", "absent", "possible", "historical", "family", "hypothetical"]

# ---------------------------------------------------------------------------
# Clinical dictionaries. Surface form -> canonical concept key.
# Deliberately includes abbreviations and synonyms, because "DM2" and "type 2
# diabetes" arriving as two different concepts is the classic downstream bug.
# ---------------------------------------------------------------------------
CONDITION_TERMS = {
    "pneumonia": "pneumonia", "cap": "pneumonia",
    "community acquired pneumonia": "pneumonia",
    "chf": "heart_failure", "congestive heart failure": "heart_failure",
    "heart failure": "heart_failure", "hfref": "heart_failure",
    "systolic heart failure": "heart_failure",
    "copd": "copd", "chronic obstructive pulmonary disease": "copd",
    "emphysema": "copd",
    "dm2": "t2dm", "dm type 2": "t2dm", "type 2 diabetes": "t2dm",
    "type ii diabetes": "t2dm", "diabetes mellitus type 2": "t2dm",
    "t2dm": "t2dm", "niddm": "t2dm",
    "diabetes": "diabetes_unspec", "dm": "diabetes_unspec",
    "htn": "hypertension", "hypertension": "hypertension",
    "high blood pressure": "hypertension",
    "mi": "myocardial_infarction", "myocardial infarction": "myocardial_infarction",
    "heart attack": "myocardial_infarction", "stemi": "myocardial_infarction",
    "nstemi": "myocardial_infarction",
    "ckd": "ckd", "chronic kidney disease": "ckd", "renal insufficiency": "ckd",
    "afib": "atrial_fibrillation", "a fib": "atrial_fibrillation",
    "atrial fibrillation": "atrial_fibrillation",
    "asthma": "asthma",
    "copd exacerbation": "copd_exacerbation",
    "chest pain": "chest_pain",
    "dyspnea": "dyspnea", "shortness of breath": "dyspnea", "sob": "dyspnea",
    "fever": "fever", "febrile": "fever",
    "cough": "cough",
    "breast cancer": "breast_cancer",
    "colon cancer": "colon_cancer", "colorectal cancer": "colon_cancer",
    "lung cancer": "lung_cancer",
    "stroke": "stroke", "cva": "stroke", "cerebrovascular accident": "stroke",
    "dvt": "dvt", "deep vein thrombosis": "dvt",
    "pe": "pulmonary_embolism", "pulmonary embolism": "pulmonary_embolism",
    "uti": "uti", "urinary tract infection": "uti",
    "sepsis": "sepsis",
    "anemia": "anemia",
    "depression": "depression",
    "obesity": "obesity",
    "osa": "sleep_apnea", "obstructive sleep apnea": "sleep_apnea",
    "gerd": "gerd", "reflux": "gerd",
    "hyperlipidemia": "hyperlipidemia", "hld": "hyperlipidemia",
    "pancreatitis": "pancreatitis",
    "cellulitis": "cellulitis",
    "aki": "aki", "acute kidney injury": "aki",
}

MEDICATION_TERMS = {
    "metformin": "metformin", "glucophage": "metformin",
    "lisinopril": "lisinopril", "zestril": "lisinopril",
    "atorvastatin": "atorvastatin", "lipitor": "atorvastatin",
    "furosemide": "furosemide", "lasix": "furosemide",
    "metoprolol": "metoprolol", "lopressor": "metoprolol",
    "amlodipine": "amlodipine", "norvasc": "amlodipine",
    "aspirin": "aspirin", "asa": "aspirin",
    "warfarin": "warfarin", "coumadin": "warfarin",
    "apixaban": "apixaban", "eliquis": "apixaban",
    "insulin glargine": "insulin_glargine", "lantus": "insulin_glargine",
    "albuterol": "albuterol", "ventolin": "albuterol",
    "prednisone": "prednisone",
    "azithromycin": "azithromycin", "zithromax": "azithromycin",
    "ceftriaxone": "ceftriaxone", "rocephin": "ceftriaxone",
    "omeprazole": "omeprazole", "prilosec": "omeprazole",
    "sertraline": "sertraline", "zoloft": "sertraline",
    "gabapentin": "gabapentin", "neurontin": "gabapentin",
    "oxycodone": "oxycodone",
    "levothyroxine": "levothyroxine", "synthroid": "levothyroxine",
    "hydrochlorothiazide": "hctz", "hctz": "hctz",
    "tiotropium": "tiotropium", "spiriva": "tiotropium",
}

ALLERGEN_TERMS = {
    "penicillin": "penicillin", "pcn": "penicillin",
    "sulfa": "sulfonamide", "sulfonamides": "sulfonamide",
    "codeine": "codeine", "morphine": "morphine",
    "latex": "latex", "shellfish": "shellfish", "peanut": "peanut",
    "iodine": "iodine", "contrast dye": "iodinated_contrast",
    "nsaids": "nsaid", "ibuprofen": "ibuprofen",
}

# ---------------------------------------------------------------------------
# Terminology subsets. Real identifiers where I am confident; the point is the
# mapping step and its failures, not the completeness of these tables.
# ---------------------------------------------------------------------------
SNOMED = {
    "pneumonia": ("233604007", "Pneumonia"),
    "heart_failure": ("84114007", "Heart failure"),
    "copd": ("13645005", "Chronic obstructive lung disease"),
    "t2dm": ("44054006", "Diabetes mellitus type 2"),
    "diabetes_unspec": ("73211009", "Diabetes mellitus"),
    "hypertension": ("38341003", "Hypertensive disorder"),
    "myocardial_infarction": ("22298006", "Myocardial infarction"),
    "ckd": ("709044004", "Chronic kidney disease"),
    "atrial_fibrillation": ("49436004", "Atrial fibrillation"),
    "asthma": ("195967001", "Asthma"),
    "chest_pain": ("29857009", "Chest pain"),
    "dyspnea": ("267036007", "Dyspnea"),
    "fever": ("386661006", "Fever"),
    "cough": ("49727002", "Cough"),
    "breast_cancer": ("254837009", "Malignant neoplasm of breast"),
    "stroke": ("230690007", "Cerebrovascular accident"),
    "dvt": ("128053003", "Deep venous thrombosis"),
    "pulmonary_embolism": ("59282003", "Pulmonary embolism"),
    "uti": ("68566005", "Urinary tract infectious disease"),
    "sepsis": ("91302008", "Sepsis"),
    "anemia": ("271737000", "Anemia"),
    "depression": ("35489007", "Depressive disorder"),
    "obesity": ("414916001", "Obesity"),
    "gerd": ("235595009", "Gastroesophageal reflux disease"),
    # DELIBERATELY ABSENT, and reported as misses by run_eval.py:
    #   copd_exacerbation, lung_cancer, colon_cancer, sleep_apnea,
    #   hyperlipidemia, pancreatitis, cellulitis, aki
    # Coverage gaps are what mapping failure analysis is FOR.
}

RXNORM = {
    "metformin": ("6809", "metformin"),
    "lisinopril": ("29046", "lisinopril"),
    "atorvastatin": ("83367", "atorvastatin"),
    "furosemide": ("4603", "furosemide"),
    "metoprolol": ("6918", "metoprolol"),
    "amlodipine": ("17767", "amlodipine"),
    "aspirin": ("1191", "aspirin"),
    "warfarin": ("11289", "warfarin"),
    "apixaban": ("1364430", "apixaban"),
    "insulin_glargine": ("274783", "insulin glargine"),
    "albuterol": ("435", "albuterol"),
    "prednisone": ("8640", "prednisone"),
    "azithromycin": ("18631", "azithromycin"),
    "omeprazole": ("7646", "omeprazole"),
    "sertraline": ("36437", "sertraline"),
    "gabapentin": ("25480", "gabapentin"),
    "oxycodone": ("7804", "oxycodone"),
    "levothyroxine": ("10582", "levothyroxine"),
    # absent on purpose: ceftriaxone, hctz, tiotropium
}
